name: dl
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5
    - opencv
    - numpy
    - scikit-learn
    - scikit-image
    - matplotlib
    - pandas
    - jupyter
    - nb_conda
    - sympy
    - pip:
        - tensorflow-gpu==1.4.0
        - keras==2.1.4